(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "magit")
(depends-on "company")
(depends-on "flycheck")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "powerline")
(depends-on "markdown-mode")

(depends-on "elpy")
(depends-on "helm")
(depends-on "auto-complete")
